### ISSUE TITLE
Error - 'ColoredRenderer' object has no attribute 'vbo_verts_face'

### ISSUE THREAD

**Issue by erezposner** [3d-hand-shape/hand-graph-cnn#15]
When running the script on real world data as per example I get the following error.
```
2019-07-16 16:13:25,003 hand_shape_pose_inference INFO: Evaluate: [8/583]	Average pose estimation error: 10.21 (mm)
2019-07-16 16:13:25,003 hand_shape_pose_inference INFO: Saving image: ./output\configs/eval_real_world_testset.yaml\pred_0.jpg
Traceback (most recent call last):
  File "/hand-graph-cnn/eval_script.py", line 111, in <module>
    main()
  File "/hand-graph-cnn/eval_script.py", line 99, in main
    est_pose_cam_xyz, file_name)
  File "\hand-graph-cnn\hand_shape_pose\util\vis.py", line 176, in save_batch_image_with_mesh_joints
    rend_img_overlay, rend_img_vp1, rend_img_vp2 = draw_mesh(mesh_renderer, image, cam_param, box, mesh_xyz)
  File "\hand-graph-cnn\hand_shape_pose\util\vis.py", line 55, in draw_mesh
    rend_img_overlay = mesh_renderer(mesh_xyz, cam=cam_for_render, img=image, do_alpha=True)
  File "\hand-graph-cnn\hand_shape_pose\util\renderer.py", line 79, in __call__
    color_id=color_id)
  File "\hand-graph-cnn\hand_shape_pose\util\renderer.py", line 225, in render_model
    imtmp = simple_renderer(rn, verts, faces, color=color)
  File "\hand-graph-cnn\hand_shape_pose\util\renderer.py", line 179, in simple_renderer
    return rn.r
  File "\lib\chumpy\ch.py", line 555, in r
    self._call_on_changed()
  File "\lib\chumpy\ch.py", line 550, in _call_on_changed
    self.on_changed(self._dirty_vars)
  File "\lib\opendr\renderer.py", line 1080, in on_changed
    self.vbo_verts_face.set_array(np.array(self.verts_by_face).astype(np.float32))
AttributeError: 'ColoredRenderer' object has no attribute 'vbo_verts_face'

Process finished with exit code 1
```

I found online a solution for this problem described here: https://github.com/polmorenoc/opendr/issues/1 

and added in util\renderer.py the following lines just before "return rn.r" in def simple_renderer(...)

```
    flipXRotation = np.array([[1.0, 0.0, 0.0, 0.0],
                              [0.0, -1.0, 0., 0.0],
                              [0.0, 0., -1.0, 0.0],
                              [0.0, 0.0, 0.0, 1.0]])
    rn.camera.openglMat = flipXRotation  # this is from setupcamera in utils
    rn.glMode = 'glfw'
    rn.sharedWin = None
    rn.overdraw = True
    rn.nsamples = 8
    rn.msaa = True  # Without anti-aliasing optimization often does not work.
    rn.initGL()
```
now I get a crash in "draw_color_image()" in opendr\renderer saying I am missing "visibillity_image" variable.
This is where I got stuck, can you please advise?

thank you

**Comment by huangshaoguang** [comment]
I get it too

**Comment by 3d-hand-shape** [comment]
I suggest you use Opendr>=0.76 and Python 2.7.
