### ISSUE TITLE
Error : "TypeError: forward() missing 1 required positional argument: 'x'"

### ISSUE THREAD

**Issue by RohitSanjay00** [3d-hand-shape/hand-graph-cnn#49]
I followed the instructions and I ran the first line of code on my CMD :- python eval_script.py --config-file "configs/eval_real_world_testset.yaml" and I got the following error.

```
Traceback (most recent call last):
  File "eval_script.py", line 111, in <module>
    main()
  File "eval_script.py", line 78, in main
    model(images, cam_params, bboxes, pose_roots, pose_scales)
  File "C:\Users\ROHIT SANJAY\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\ROHIT SANJAY\Desktop\hand-graph-cnn-master\hand_shape_pose\model\shape_pose_network.py", line 87, in forward
    est_hm_list, encoding = self.net_hm(images)
  File "C:\Users\ROHIT SANJAY\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'x'

```

any suggestions?

**Comment by HanXiaoyou** [comment]
I also encountered this problem, which should be statically related to the version forward after pytorch 1.3.0. The problem should be the project [spectral_graph_convnets](https://github.com/xbresson/spectral_graph_convnets) with the function my_sparse_mm for its forward in fold hand-graph-cnn/hand_shape_pose/util/, rather this project. My solution is to change all my_sparse_mm() to my_sparse_mm().apply(). For example, change [            x1 = my_sparse_mm()(L, x0)  # V x Fin*B](https://github.com/3d-hand-shape/hand-graph-cnn/blob/2f59da3e7d9d78b8de0549b9600df6f44ca90fa0/hand_shape_pose/model/net_mesh_pose.py#L93) to `x1 = my_sparse_mm().apply(L, x0) `
